// Generated by gencpp from file rl_model/GetQuadcopterData.msg
// DO NOT EDIT!


#ifndef RL_MODEL_MESSAGE_GETQUADCOPTERDATA_H
#define RL_MODEL_MESSAGE_GETQUADCOPTERDATA_H

#include <ros/service_traits.h>


#include <rl_model/GetQuadcopterDataRequest.h>
#include <rl_model/GetQuadcopterDataResponse.h>


namespace rl_model
{

struct GetQuadcopterData
{

typedef GetQuadcopterDataRequest Request;
typedef GetQuadcopterDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetQuadcopterData
} // namespace rl_model


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rl_model::GetQuadcopterData > {
  static const char* value()
  {
    return "11c48fac5a9fde0bc6a969a66522b5e4";
  }

  static const char* value(const ::rl_model::GetQuadcopterData&) { return value(); }
};

template<>
struct DataType< ::rl_model::GetQuadcopterData > {
  static const char* value()
  {
    return "rl_model/GetQuadcopterData";
  }

  static const char* value(const ::rl_model::GetQuadcopterData&) { return value(); }
};


// service_traits::MD5Sum< ::rl_model::GetQuadcopterDataRequest> should match 
// service_traits::MD5Sum< ::rl_model::GetQuadcopterData > 
template<>
struct MD5Sum< ::rl_model::GetQuadcopterDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rl_model::GetQuadcopterData >::value();
  }
  static const char* value(const ::rl_model::GetQuadcopterDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rl_model::GetQuadcopterDataRequest> should match 
// service_traits::DataType< ::rl_model::GetQuadcopterData > 
template<>
struct DataType< ::rl_model::GetQuadcopterDataRequest>
{
  static const char* value()
  {
    return DataType< ::rl_model::GetQuadcopterData >::value();
  }
  static const char* value(const ::rl_model::GetQuadcopterDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rl_model::GetQuadcopterDataResponse> should match 
// service_traits::MD5Sum< ::rl_model::GetQuadcopterData > 
template<>
struct MD5Sum< ::rl_model::GetQuadcopterDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rl_model::GetQuadcopterData >::value();
  }
  static const char* value(const ::rl_model::GetQuadcopterDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rl_model::GetQuadcopterDataResponse> should match 
// service_traits::DataType< ::rl_model::GetQuadcopterData > 
template<>
struct DataType< ::rl_model::GetQuadcopterDataResponse>
{
  static const char* value()
  {
    return DataType< ::rl_model::GetQuadcopterData >::value();
  }
  static const char* value(const ::rl_model::GetQuadcopterDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RL_MODEL_MESSAGE_GETQUADCOPTERDATA_H
