(cl:defpackage rl_model-srv
  (:use )
  (:export
   "GETQUADCOPTERDATA"
   "<GETQUADCOPTERDATA-REQUEST>"
   "GETQUADCOPTERDATA-REQUEST"
   "<GETQUADCOPTERDATA-RESPONSE>"
   "GETQUADCOPTERDATA-RESPONSE"
  ))

