// Generated by gencpp from file simulation_control/GetOpjectData.msg
// DO NOT EDIT!


#ifndef SIMULATION_CONTROL_MESSAGE_GETOPJECTDATA_H
#define SIMULATION_CONTROL_MESSAGE_GETOPJECTDATA_H

#include <ros/service_traits.h>


#include <simulation_control/GetOpjectDataRequest.h>
#include <simulation_control/GetOpjectDataResponse.h>


namespace simulation_control
{

struct GetOpjectData
{

typedef GetOpjectDataRequest Request;
typedef GetOpjectDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetOpjectData
} // namespace simulation_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simulation_control::GetOpjectData > {
  static const char* value()
  {
    return "9dc8a94b294d83779a3e911e4c2ef7fb";
  }

  static const char* value(const ::simulation_control::GetOpjectData&) { return value(); }
};

template<>
struct DataType< ::simulation_control::GetOpjectData > {
  static const char* value()
  {
    return "simulation_control/GetOpjectData";
  }

  static const char* value(const ::simulation_control::GetOpjectData&) { return value(); }
};


// service_traits::MD5Sum< ::simulation_control::GetOpjectDataRequest> should match 
// service_traits::MD5Sum< ::simulation_control::GetOpjectData > 
template<>
struct MD5Sum< ::simulation_control::GetOpjectDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simulation_control::GetOpjectData >::value();
  }
  static const char* value(const ::simulation_control::GetOpjectDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulation_control::GetOpjectDataRequest> should match 
// service_traits::DataType< ::simulation_control::GetOpjectData > 
template<>
struct DataType< ::simulation_control::GetOpjectDataRequest>
{
  static const char* value()
  {
    return DataType< ::simulation_control::GetOpjectData >::value();
  }
  static const char* value(const ::simulation_control::GetOpjectDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simulation_control::GetOpjectDataResponse> should match 
// service_traits::MD5Sum< ::simulation_control::GetOpjectData > 
template<>
struct MD5Sum< ::simulation_control::GetOpjectDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simulation_control::GetOpjectData >::value();
  }
  static const char* value(const ::simulation_control::GetOpjectDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulation_control::GetOpjectDataResponse> should match 
// service_traits::DataType< ::simulation_control::GetOpjectData > 
template<>
struct DataType< ::simulation_control::GetOpjectDataResponse>
{
  static const char* value()
  {
    return DataType< ::simulation_control::GetOpjectData >::value();
  }
  static const char* value(const ::simulation_control::GetOpjectDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMULATION_CONTROL_MESSAGE_GETOPJECTDATA_H
