// Generated by gencpp from file simulation_control/GetQuadcopterData.msg
// DO NOT EDIT!


#ifndef SIMULATION_CONTROL_MESSAGE_GETQUADCOPTERDATA_H
#define SIMULATION_CONTROL_MESSAGE_GETQUADCOPTERDATA_H

#include <ros/service_traits.h>


#include <simulation_control/GetQuadcopterDataRequest.h>
#include <simulation_control/GetQuadcopterDataResponse.h>


namespace simulation_control
{

struct GetQuadcopterData
{

typedef GetQuadcopterDataRequest Request;
typedef GetQuadcopterDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetQuadcopterData
} // namespace simulation_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simulation_control::GetQuadcopterData > {
  static const char* value()
  {
    return "bda7fb9bcb992692c1da67536514aeb3";
  }

  static const char* value(const ::simulation_control::GetQuadcopterData&) { return value(); }
};

template<>
struct DataType< ::simulation_control::GetQuadcopterData > {
  static const char* value()
  {
    return "simulation_control/GetQuadcopterData";
  }

  static const char* value(const ::simulation_control::GetQuadcopterData&) { return value(); }
};


// service_traits::MD5Sum< ::simulation_control::GetQuadcopterDataRequest> should match 
// service_traits::MD5Sum< ::simulation_control::GetQuadcopterData > 
template<>
struct MD5Sum< ::simulation_control::GetQuadcopterDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simulation_control::GetQuadcopterData >::value();
  }
  static const char* value(const ::simulation_control::GetQuadcopterDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulation_control::GetQuadcopterDataRequest> should match 
// service_traits::DataType< ::simulation_control::GetQuadcopterData > 
template<>
struct DataType< ::simulation_control::GetQuadcopterDataRequest>
{
  static const char* value()
  {
    return DataType< ::simulation_control::GetQuadcopterData >::value();
  }
  static const char* value(const ::simulation_control::GetQuadcopterDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simulation_control::GetQuadcopterDataResponse> should match 
// service_traits::MD5Sum< ::simulation_control::GetQuadcopterData > 
template<>
struct MD5Sum< ::simulation_control::GetQuadcopterDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simulation_control::GetQuadcopterData >::value();
  }
  static const char* value(const ::simulation_control::GetQuadcopterDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulation_control::GetQuadcopterDataResponse> should match 
// service_traits::DataType< ::simulation_control::GetQuadcopterData > 
template<>
struct DataType< ::simulation_control::GetQuadcopterDataResponse>
{
  static const char* value()
  {
    return DataType< ::simulation_control::GetQuadcopterData >::value();
  }
  static const char* value(const ::simulation_control::GetQuadcopterDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMULATION_CONTROL_MESSAGE_GETQUADCOPTERDATA_H
