// Generated by gencpp from file simulation_control/ResetObjectPosition.msg
// DO NOT EDIT!


#ifndef SIMULATION_CONTROL_MESSAGE_RESETOBJECTPOSITION_H
#define SIMULATION_CONTROL_MESSAGE_RESETOBJECTPOSITION_H

#include <ros/service_traits.h>


#include <simulation_control/ResetObjectPositionRequest.h>
#include <simulation_control/ResetObjectPositionResponse.h>


namespace simulation_control
{

struct ResetObjectPosition
{

typedef ResetObjectPositionRequest Request;
typedef ResetObjectPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetObjectPosition
} // namespace simulation_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simulation_control::ResetObjectPosition > {
  static const char* value()
  {
    return "b9c36716c61bd35f89c1c4d65dcd1b88";
  }

  static const char* value(const ::simulation_control::ResetObjectPosition&) { return value(); }
};

template<>
struct DataType< ::simulation_control::ResetObjectPosition > {
  static const char* value()
  {
    return "simulation_control/ResetObjectPosition";
  }

  static const char* value(const ::simulation_control::ResetObjectPosition&) { return value(); }
};


// service_traits::MD5Sum< ::simulation_control::ResetObjectPositionRequest> should match 
// service_traits::MD5Sum< ::simulation_control::ResetObjectPosition > 
template<>
struct MD5Sum< ::simulation_control::ResetObjectPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simulation_control::ResetObjectPosition >::value();
  }
  static const char* value(const ::simulation_control::ResetObjectPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulation_control::ResetObjectPositionRequest> should match 
// service_traits::DataType< ::simulation_control::ResetObjectPosition > 
template<>
struct DataType< ::simulation_control::ResetObjectPositionRequest>
{
  static const char* value()
  {
    return DataType< ::simulation_control::ResetObjectPosition >::value();
  }
  static const char* value(const ::simulation_control::ResetObjectPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simulation_control::ResetObjectPositionResponse> should match 
// service_traits::MD5Sum< ::simulation_control::ResetObjectPosition > 
template<>
struct MD5Sum< ::simulation_control::ResetObjectPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simulation_control::ResetObjectPosition >::value();
  }
  static const char* value(const ::simulation_control::ResetObjectPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulation_control::ResetObjectPositionResponse> should match 
// service_traits::DataType< ::simulation_control::ResetObjectPosition > 
template<>
struct DataType< ::simulation_control::ResetObjectPositionResponse>
{
  static const char* value()
  {
    return DataType< ::simulation_control::ResetObjectPosition >::value();
  }
  static const char* value(const ::simulation_control::ResetObjectPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMULATION_CONTROL_MESSAGE_RESETOBJECTPOSITION_H
