// Generated by gencpp from file simulation_control/ResetPositionState.msg
// DO NOT EDIT!


#ifndef SIMULATION_CONTROL_MESSAGE_RESETPOSITIONSTATE_H
#define SIMULATION_CONTROL_MESSAGE_RESETPOSITIONSTATE_H

#include <ros/service_traits.h>


#include <simulation_control/ResetPositionStateRequest.h>
#include <simulation_control/ResetPositionStateResponse.h>


namespace simulation_control
{

struct ResetPositionState
{

typedef ResetPositionStateRequest Request;
typedef ResetPositionStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetPositionState
} // namespace simulation_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simulation_control::ResetPositionState > {
  static const char* value()
  {
    return "b34df3ca8ca98e0220d79d2c697c2943";
  }

  static const char* value(const ::simulation_control::ResetPositionState&) { return value(); }
};

template<>
struct DataType< ::simulation_control::ResetPositionState > {
  static const char* value()
  {
    return "simulation_control/ResetPositionState";
  }

  static const char* value(const ::simulation_control::ResetPositionState&) { return value(); }
};


// service_traits::MD5Sum< ::simulation_control::ResetPositionStateRequest> should match 
// service_traits::MD5Sum< ::simulation_control::ResetPositionState > 
template<>
struct MD5Sum< ::simulation_control::ResetPositionStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simulation_control::ResetPositionState >::value();
  }
  static const char* value(const ::simulation_control::ResetPositionStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulation_control::ResetPositionStateRequest> should match 
// service_traits::DataType< ::simulation_control::ResetPositionState > 
template<>
struct DataType< ::simulation_control::ResetPositionStateRequest>
{
  static const char* value()
  {
    return DataType< ::simulation_control::ResetPositionState >::value();
  }
  static const char* value(const ::simulation_control::ResetPositionStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simulation_control::ResetPositionStateResponse> should match 
// service_traits::MD5Sum< ::simulation_control::ResetPositionState > 
template<>
struct MD5Sum< ::simulation_control::ResetPositionStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simulation_control::ResetPositionState >::value();
  }
  static const char* value(const ::simulation_control::ResetPositionStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulation_control::ResetPositionStateResponse> should match 
// service_traits::DataType< ::simulation_control::ResetPositionState > 
template<>
struct DataType< ::simulation_control::ResetPositionStateResponse>
{
  static const char* value()
  {
    return DataType< ::simulation_control::ResetPositionState >::value();
  }
  static const char* value(const ::simulation_control::ResetPositionStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMULATION_CONTROL_MESSAGE_RESETPOSITIONSTATE_H
