// Generated by gencpp from file simulation_control/TakeOffAndLand.msg
// DO NOT EDIT!


#ifndef SIMULATION_CONTROL_MESSAGE_TAKEOFFANDLAND_H
#define SIMULATION_CONTROL_MESSAGE_TAKEOFFANDLAND_H

#include <ros/service_traits.h>


#include <simulation_control/TakeOffAndLandRequest.h>
#include <simulation_control/TakeOffAndLandResponse.h>


namespace simulation_control
{

struct TakeOffAndLand
{

typedef TakeOffAndLandRequest Request;
typedef TakeOffAndLandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TakeOffAndLand
} // namespace simulation_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simulation_control::TakeOffAndLand > {
  static const char* value()
  {
    return "318f069335e84d20f7af479a87c22959";
  }

  static const char* value(const ::simulation_control::TakeOffAndLand&) { return value(); }
};

template<>
struct DataType< ::simulation_control::TakeOffAndLand > {
  static const char* value()
  {
    return "simulation_control/TakeOffAndLand";
  }

  static const char* value(const ::simulation_control::TakeOffAndLand&) { return value(); }
};


// service_traits::MD5Sum< ::simulation_control::TakeOffAndLandRequest> should match 
// service_traits::MD5Sum< ::simulation_control::TakeOffAndLand > 
template<>
struct MD5Sum< ::simulation_control::TakeOffAndLandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simulation_control::TakeOffAndLand >::value();
  }
  static const char* value(const ::simulation_control::TakeOffAndLandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulation_control::TakeOffAndLandRequest> should match 
// service_traits::DataType< ::simulation_control::TakeOffAndLand > 
template<>
struct DataType< ::simulation_control::TakeOffAndLandRequest>
{
  static const char* value()
  {
    return DataType< ::simulation_control::TakeOffAndLand >::value();
  }
  static const char* value(const ::simulation_control::TakeOffAndLandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simulation_control::TakeOffAndLandResponse> should match 
// service_traits::MD5Sum< ::simulation_control::TakeOffAndLand > 
template<>
struct MD5Sum< ::simulation_control::TakeOffAndLandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simulation_control::TakeOffAndLand >::value();
  }
  static const char* value(const ::simulation_control::TakeOffAndLandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulation_control::TakeOffAndLandResponse> should match 
// service_traits::DataType< ::simulation_control::TakeOffAndLand > 
template<>
struct DataType< ::simulation_control::TakeOffAndLandResponse>
{
  static const char* value()
  {
    return DataType< ::simulation_control::TakeOffAndLand >::value();
  }
  static const char* value(const ::simulation_control::TakeOffAndLandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMULATION_CONTROL_MESSAGE_TAKEOFFANDLAND_H
