// Generated by gencpp from file simulation_control/TakeOffAndLandRequest.msg
// DO NOT EDIT!


#ifndef SIMULATION_CONTROL_MESSAGE_TAKEOFFANDLANDREQUEST_H
#define SIMULATION_CONTROL_MESSAGE_TAKEOFFANDLANDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulation_control
{
template <class ContainerAllocator>
struct TakeOffAndLandRequest_
{
  typedef TakeOffAndLandRequest_<ContainerAllocator> Type;

  TakeOffAndLandRequest_()
    : model_prefix()  {
    }
  TakeOffAndLandRequest_(const ContainerAllocator& _alloc)
    : model_prefix(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _model_prefix_type;
  _model_prefix_type model_prefix;





  typedef boost::shared_ptr< ::simulation_control::TakeOffAndLandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulation_control::TakeOffAndLandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TakeOffAndLandRequest_

typedef ::simulation_control::TakeOffAndLandRequest_<std::allocator<void> > TakeOffAndLandRequest;

typedef boost::shared_ptr< ::simulation_control::TakeOffAndLandRequest > TakeOffAndLandRequestPtr;
typedef boost::shared_ptr< ::simulation_control::TakeOffAndLandRequest const> TakeOffAndLandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulation_control::TakeOffAndLandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulation_control::TakeOffAndLandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simulation_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simulation_control::TakeOffAndLandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulation_control::TakeOffAndLandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulation_control::TakeOffAndLandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulation_control::TakeOffAndLandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulation_control::TakeOffAndLandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulation_control::TakeOffAndLandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulation_control::TakeOffAndLandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "318f069335e84d20f7af479a87c22959";
  }

  static const char* value(const ::simulation_control::TakeOffAndLandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x318f069335e84d20ULL;
  static const uint64_t static_value2 = 0xf7af479a87c22959ULL;
};

template<class ContainerAllocator>
struct DataType< ::simulation_control::TakeOffAndLandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulation_control/TakeOffAndLandRequest";
  }

  static const char* value(const ::simulation_control::TakeOffAndLandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulation_control::TakeOffAndLandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string model_prefix\n\
";
  }

  static const char* value(const ::simulation_control::TakeOffAndLandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulation_control::TakeOffAndLandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.model_prefix);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TakeOffAndLandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulation_control::TakeOffAndLandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulation_control::TakeOffAndLandRequest_<ContainerAllocator>& v)
  {
    s << indent << "model_prefix: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.model_prefix);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATION_CONTROL_MESSAGE_TAKEOFFANDLANDREQUEST_H
